#!/usr/bin/env python3
"""
bundle-standalone.py — pack a workshop-design-system template into ONE
fully self-contained HTML file: every linked css/*.css and js/*.js file
inlined, every font referenced from css/fonts-sketch.css embedded as a
base64 data URI. Zero external requests, zero relative-path dependency
on the repo's folder structure — the output file can be emailed, dropped
anywhere, opened directly.

Pure standard library — no pip install, matching the repo's own
zero-dependency philosophy. Regex-based on content markers (not line
numbers), so it doesn't break if a template gains or loses a line above
the parts it's extracting.

Usage:
    python3 scripts/bundle-standalone.py templates/sketch-dashboard.he.html
    python3 scripts/bundle-standalone.py templates/sketch-dashboard.he.html -o out.html

The input file must follow this repo's template convention: a run of
<link rel="stylesheet" href="../css/...."> tags (optionally one with
media="print"), one Google-Fonts CDN <link> (dropped — it only ever
serves the non-sketchbook body/display fonts, never the self-hosted
sketchbook ones, and is irrelevant to a sketchbook-only deck), a single
inline <style>...</style> block, then <body>, then a run of
<script src="../js/....js"> tags, then exactly one inline
<script>...</script> block at the end.
"""
import argparse
import base64
import mimetypes
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def read(path):
    return Path(path).read_text(encoding='utf-8')


def inline_fonts(css_text, css_file_dir):
    """Replace every url('relative/path/to/font.woff2') in a stylesheet
    with a base64 data: URI, resolved relative to the stylesheet's own
    directory (matches normal CSS url() resolution)."""
    def repl(m):
        rel = m.group(1)
        if rel.startswith(('data:', 'http:', 'https:')):
            return m.group(0)
        font_path = (css_file_dir / rel).resolve()
        data = font_path.read_bytes()
        mime = mimetypes.guess_type(str(font_path))[0] or 'application/octet-stream'
        if font_path.suffix == '.woff2':
            mime = 'font/woff2'
        b64 = base64.b64encode(data).decode('ascii')
        return f"url('data:{mime};base64,{b64}')"
    return re.sub(r"url\(['\"]?([^'\")]+)['\"]?\)", repl, css_text)


def bundle(input_path: Path) -> str:
    src = read(input_path)
    src_dir = input_path.resolve().parent

    # 1. Local stylesheet <link> tags, in document order (skip CDN ones).
    css_blocks = []
    for m in re.finditer(r'<link\s+rel="stylesheet"\s+href="([^"]+)"[^>]*>', src):
        href = m.group(1)
        if href.startswith(('http:', 'https:')):
            continue  # Google Fonts CDN etc. — never part of the sketchbook system itself
        css_path = (src_dir / href).resolve()
        css_text = read(css_path)
        if css_path.name == 'fonts-sketch.css':
            css_text = inline_fonts(css_text, css_path.parent)
        css_blocks.append(f"/* ==== {href} ==== */\n{css_text}")
    combined_css = "\n\n".join(css_blocks)

    # 2. The template's own inline <style>...</style> block (page-local CSS).
    style_m = re.search(r'<style>(.*?)</style>', src, re.S)
    local_style = style_m.group(1) if style_m else ''

    # 3. Body content up to (not including) the first <script src="...">.
    body_m = re.search(r'<body>(.*?)<script\s+src=', src, re.S)
    if not body_m:
        sys.exit('Could not find <body> ... <script src=...> — unexpected template shape.')
    body_content = body_m.group(1)

    # 4. Every <script src="../js/....js"></script>, in order.
    js_blocks = []
    for m in re.finditer(r'<script\s+src="([^"]+)"></script>', src):
        href = m.group(1)
        js_path = (src_dir / href).resolve()
        js_blocks.append(f"/* ==== {href} ==== */\n{read(js_path)}")
    combined_js = "\n\n".join(js_blocks)

    # 5. The final inline <script>...</script> (the page's own deck/init logic).
    inline_scripts = re.findall(r'<script>(?!\s*src)(.*?)</script>', src, re.S)
    if not inline_scripts:
        sys.exit('Could not find a bare inline <script>...</script> block.')
    inline_script_body = inline_scripts[-1]

    title_m = re.search(r'<title>(.*?)</title>', src)
    title = title_m.group(1) if title_m else 'Standalone deck'
    lang_m = re.search(r'<html\s+([^>]*)>', src)
    html_attrs = lang_m.group(1) if lang_m else 'lang="en" dir="ltr"'

    return f'''<!DOCTYPE html>
<html {html_attrs}>
<head>
<meta charset="UTF-8">
<title>{title} (standalone)</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- ============================================================
     Fully self-contained build — every css/js/font file this
     template depends on is inlined below (fonts as base64 data
     URIs). No external requests, no relative paths. Generated by
     scripts/bundle-standalone.py from {input_path.name}.
     ============================================================ -->
<style>
{combined_css}
</style>
<style>
{local_style}</style>
</head>
<body>
{body_content}<script>
{inline_script_body}</script>
</body>
</html>
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('input', help='Path to a template HTML file (e.g. templates/sketch-dashboard.he.html)')
    ap.add_argument('-o', '--output', help='Output path (default: <input>.standalone.html next to the input)')
    args = ap.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        sys.exit(f'No such file: {input_path}')

    out = bundle(input_path)

    if args.output:
        output_path = Path(args.output)
    else:
        output_path = input_path.with_name(re.sub(r'\.html$', '.standalone.html', input_path.name))

    output_path.write_text(out, encoding='utf-8')
    print(f'Wrote {output_path} ({len(out):,} bytes)')


if __name__ == '__main__':
    main()
